# Generated by Django 6.1 on 2026-09-02 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="content",
            field=models.TextField(null=True),
        ),
    ]
